### ISSUE TITLE
Give feedback while waiting for shortened url to display

### ISSUE THREAD

**Issue by danerwilliams** [danerwilliams/pstb.in#2]
while waiting for the shortened url to display, show some sort of spinner or other loading icon / animation

**Comment by antithalian** [comment]
Per [this](https://medium.com/@ryanallen_com/build-an-animated-svg-loading-icon-in-5-minutes-c90058b44610) + [this](https://codepen.io/ryanallen/pen/OPpbbR), can probably make a quick SVG one.

Or just fill the text box with some unicode bullets that add up... (e.g. * -> ** -> *** -> *...).

**Comment by danerwilliams** [comment]
I think there's a spinner you can use that's in bootstrap too. Could work nicely since we're already using bootstrap components.

**Comment by antithalian** [comment]
Oh yeah, that'd be good. No need to reinvent the wheel if bootstrap already did it for us.

**Comment by antithalian** [comment]
So bootstrap has [this](https://getbootstrap.com/docs/4.2/components/spinners/). I bet we could get it to show "loading" where the text will go and then a spinner where the "copy" symbol appears. I'll work on it in a bit, unless you want to just do it.

**Comment by danerwilliams** [comment]
Yeah that sounds perfect.
