### ISSUE TITLE
Add https support?

### ISSUE THREAD

**Issue by antithalian** [danerwilliams/pstb.in#8]
Unsure how easy it is with the Chalice/AWS Lambda architecture, but adding HTTPS seems like a good idea.

**Comment by danerwilliams** [comment]
Yeah I'm hosting it through s3 which seems to only be http by default. I think there may be a way to enable https with cloud front or another service. I can look into it.

**Comment by danerwilliams** [comment]
client should now work with https (implemented with cloudfront and acm), although file serving must remain http due to s3 limitations

**Comment by danerwilliams** [comment]
> client should now work with https (implemented with cloudfront and acm), although file serving must remain http due to s3 limitations

I'm mistaken and it actually does do https for file serving too. So should be https all around.

**Comment by antithalian** [comment]
Nice work!
